
import random
import math
import time
import numpy as np
import matplotlib.pyplot as plt


#1.1 Test if the RNG generates random numbers
random_seq = [random.random()*1000000 for i in range(1,1000000)]
buckets = {}
for y in random_seq:
    key = round(y)%1000
    buckets[key]=buckets.get(key,0)+1
expected = [1000]*1000
observed = [v for v in buckets.values()]

#Plot the CDF of expected values
plt.plot(range(0,1000), np.cumsum(expected)/1000000, label='expected', color='g')
plt.show()

#Plot the CDF of observed values
plt.plot(range(0,1000), np.cumsum(observed)/1000000, label='observed', color='g')
plt.show()


#1.3 Test if the two sequences generated by RNG are different
#Generate random sequences with the same seed and visualize the correlation
random.seed(1)
random_seq1 = [random.random()*1000000 for i in range(1,1000000)]
random.seed(1)
random_seq2 = [random.random()*1000000 for i in range(1,1000000)]
plt.scatter(random_seq1, random_seq2, color='b')
plt.show()

#Generate random sequences with different seeds and visualize the correlation
random.seed(1)
random_seq1 = [random.random()*1000000 for i in range(1,1000000)]
random.seed(2)
random_seq2 = [random.random()*1000000 for i in range(1,1000000)]
plt.scatter(random_seq1, random_seq2, color='b')
plt.show()

